# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import sample_paran_groups as module_0


def test_case_0():
    str_0 = "gW*G)Q\tM&JkO>&%4?H.g\x0c"
    module_0.separate_paren_groups(str_0)


def test_case_1():
    str_0 = '(}5"j&*pNm)<o}u" hlHT-'
    module_0.separate_paren_groups(str_0)
